In [2]:
import pandas as pd

In [3]:
emp = pd.read_excel(r"C:\Users\Homes\OneDrive\Desktop\data projects\practise_2\employees_details.xlsx")
dep = pd.read_excel(r"C:\Users\Homes\OneDrive\Desktop\data projects\practise_2\department_details.xlsx")
emp.head(3)
dep.head(3)

,Department_id,Department_name,Location,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,200,Admin,Ranchi,NaN,NaN,NaN,NaN
1,210,Sales,Ranchi,NaN,NaN,NaN,NaN
2,220,Computer,Ranchi,NaN,NaN,NaN,NaN

In [4]:
merged_tt = pd.merge(emp,dep,on="Department_id",how= "outer")
print(merged_tt)

    Employee_id Last_name first_name  age  salary  Department_id  \
0           100   sharma       viren   25   25000            200
1           101   sharma     dhriraj   26   25000            210
2           102     singh     rakesh   63   35001            220
3           103     singh     nikhil   21   65254            230
4           104     singh     saurav   54   87542            240
..          ...       ...        ...  ...     ...            ...
80          180    kettie       tony   30   63210           1010
81          181     lampo      clint   22   56320           1020
82          182     resto       ruky   29   45000           1030
83          183   william    patrick   29   21453           1040
84          184     sakes      arthu   28   65000           1050

   Department_name   Location  Unnamed: 3  Unnamed: 4  Unnamed: 5 Unnamed: 6
0            Admin     Ranchi         NaN         NaN         NaN        NaN
1            Sales     Ranchi         NaN         NaN         NaN        NaN
2         Computer     Ranchi         NaN         NaN         NaN        NaN
3          General     Ranchi         NaN         NaN         NaN        NaN
4        marketing     Ranchi         NaN         NaN         NaN        NaN
..             ...        ...         ...         ...         ...        ...
80        security  benguluru         NaN         NaN         NaN        NaN
81         finance  benguluru         NaN         NaN         NaN        NaN
82    aminstration  benguluru         NaN         NaN         NaN        NaN
83         analyst  benguluru         NaN         NaN         NaN        NaN
84      maintances  benguluru         NaN         NaN         NaN        NaN

[85 rows x 12 columns]

In [5]:
merged_tt.head(5)

,Employee_id,Last_name,first_name,age,salary,Department_id,Department_name,Location,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,100,sharma,viren,25,25000,200,Admin,Ranchi,NaN,NaN,NaN,NaN
1,101,sharma,dhriraj,26,25000,210,Sales,Ranchi,NaN,NaN,NaN,NaN
2,102,singh,rakesh,63,35001,220,Computer,Ranchi,NaN,NaN,NaN,NaN
3,103,singh,nikhil,21,65254,230,General,Ranchi,NaN,NaN,NaN,NaN
4,104,singh,saurav,54,87542,240,marketing,Ranchi,NaN,NaN,NaN,NaN

In [6]:
merged_tt.dropna(axis=1)

,Employee_id,Last_name,first_name,age,salary,Department_id,Department_name,Location
0,100,sharma,viren,25,25000,200,Admin,Ranchi
1,101,sharma,dhriraj,26,25000,210,Sales,Ranchi
2,102,singh,rakesh,63,35001,220,Computer,Ranchi
3,103,singh,nikhil,21,65254,230,General,Ranchi
4,104,singh,saurav,54,87542,240,marketing,Ranchi
...,...,...,...,...,...,...,...,...
80,180,kettie,tony,30,63210,1010,security,benguluru
81,181,lampo,clint,22,56320,1020,finance,benguluru
82,182,resto,ruky,29,45000,1030,aminstration,benguluru
83,183,william,patrick,29,21453,1040,analyst,benguluru
84,184,sakes,arthu,28,65000,1050,maintances,benguluru

In [8]:
pivotTables = merged_tt.pivot_table(index="Department_name", columns="Location", values="first_name", aggfunc='first')
print(pivotTables)

Location             Ranchi  benguluru  kolkata      patna varnasi
Department_name
Admin                 viren       ravi    viren       ravi  ashish
Computer             rakesh      bablu   rakesh      bablu   shiva
General              nikhil  dinbandhu   nikhil  dinbandhu   rahul
Sales               dhriraj       papu  dhriraj       papu   harsh
aminstration          aryan       ruky    aryan      akash  robert
analyst               ayush    patrick    ayush     chandu  albert
cyber security        arjun      pandy    arjun      divya  tanzil
datsbase             adarsh    william   adarsh    pratham    azad
debugger             vikash      bandy   vikash       raju   tiger
designing            samrat      sandy   samrat      shyam   bunty
finance                 raj      clint      raj    anirudh     jon
human resourses       rudra       ramu    rudra      bittu  bubbly
maintances            varun      arthu    varun      mintu  martin
marketing            saurav     joseph   saurav     ritvik   tazad
security            gijnesh       tony  gijnesh       kitu     jon
software developer    akash     xander    akash      rishu  joseph
tetster              suresh      steve   suresh      bunty  robert

In [8]:
# this is the file to have to save the csv file 
pivotTables.to_csv(r"C:\Users\Homes\OneDrive\Desktop\data projects\practise_2\pivotTables.csv")